apiVersion: v1
kind: Secret
metadata:
  name: es-secrets
data:
  # echo -n 'elastic' | base64
  ELASTICSEARCH_USERNAME: ZWxhc3RpYw==
  # echo -n 'vczz5ccbl2sbtggd6gn826d7' | base64
  ELASTICSEARCH_PASSWORD: dmN6ejVjY2JsMnNidGdnZDZnbjgyNmQ3
  # echo -n ''["https://elasticsearch-sample-es-http.default.svc.cluster.local:9200"]'' | base64
  ELASTICSEARCH_HOSTS: W2h0dHBzOi8vZWxhc3RpY3NlYXJjaC1zYW1wbGUtZXMtaHR0cC5kZWZhdWx0LnN2Yy5jbHVzdGVyLmxvY2FsOjkyMDBd
  # echo -n 'https://kibana-sample-kb-http.default.svc.cluster.local:5601' | base64
  KIBANA_HOST: aHR0cHM6Ly9raWJhbmEtc2FtcGxlLWtiLWh0dHAuZGVmYXVsdC5zdmMuY2x1c3Rlci5sb2NhbDo1NjAx